theme: jekyll-theme-modernist
title: Froggum Icon Editor
description: Pixel perfect icons
url: https://sapoturge.github.io/froggum
icon: /assets/images/froggum_icons/48.svg
tabicon: /assets/images/froggum_icons/16.svg
background-color: "#C2FA96"
title-color: "#690"
bold-color: "#242"
latest: 0.2
dev: 0.3
collections:
  - doc_versions
